name: build an integrate image to Dockerhub

on: 
  push: 
    branches: [main]
  workflow_dispatch : 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build docker image
        run: |
          docker build -t nytendry7/my_python_web_app-web .
      - name : Login to Dockerhub
        uses: docker/login-action@v2
        with: 
          username: nytendry7
          password: dckr_pat_xu44y9lr1nrCWzktvjhNVMT7ja4
      - name: push to Docker hub
        run: |
          docker push nytendry7/my_python_web_app-web